# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samehadago', '0002_auto_20171207_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='text',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
